ROOT = ../../..

### Include should be before any settings so that settings can override
### if desired.
include $(ROOT)/etc/Makefile_root

OVM_PKG        =
SOURCE         =
ORUN           = OVM_TESTHOME=${OVM_HOME}; export OVM_TESTHOME;irun -f compile_ius.f

